### ISSUE TITLE
I am having this Import error. Don't know why

### ISSUE THREAD

**Issue by ghost** [abzargar/COVID-Classifier#1]
runfile('C:/Users/SANA/Downloads/COVID-Classifier-master/preprocess_images.py', wdir='C:/Users/SANA/Downloads/COVID-Classifier-master')
Traceback (most recent call last):

  File "<ipython-input-2-d761588ace4f>", line 1, in <module>
    runfile('C:/Users/SANA/Downloads/COVID-Classifier-master/preprocess_images.py', wdir='C:/Users/SANA/Downloads/COVID-Classifier-master')

  File "G:\python\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "G:\python\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/SANA/Downloads/COVID-Classifier-master/preprocess_images.py", line 4, in <module>
    import skimage.io as io

  File "G:\python\lib\site-packages\skimage\io\__init__.py", line 11, in <module>
    from ._io import *

  File "G:\python\lib\site-packages\skimage\io\_io.py", line 7, in <module>
    from ..color import rgb2grey

  File "G:\python\lib\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,

  File "G:\python\lib\site-packages\skimage\color\colorconv.py", line 60, in <module>
    from ..util import dtype, dtype_limits

  File "G:\python\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
    from .arraycrop import crop

  File "G:\python\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths

ImportError: cannot import name '_validate_lengths'

**Comment by abzargar** [comment]
Thank you for your email. I will check it out and will let you know.

Sincerely,


Abolfazl Zargari


Ph.D. student and research assistant

Electrical and Computer Engineering Department

The University of California, Santa Cruz
Email: abzargar@ucsc.edu
