### ISSUE TITLE
cv2

### ISSUE THREAD

**Issue by kirillportfolio** [abzargar/COVID-Classifier#4]
thank you for your work,

can you please tell me which version of opencv should I use to reproduce your result and by which command to install it (cv2) ?

how can I solve this error ?

(base) C:\Users\Admin\Desktop\COVID-Classifier-master>python extract_features.py
Traceback (most recent call last):
  File "extract_features.py", line 12, in <module>
    from utils import*
  File "C:\Users\Admin\Desktop\COVID-Classifier-master\utils.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by kirillportfolio** [comment]
by the way I tried to use this 
pip install opencv-python
https://stackoverflow.com/questions/19876079/cannot-find-module-cv2-when-using-opencv
and get this results:

Successfully installed opencv-python-4.5.4.60

(base) C:\Users\Admin\Desktop\COVID-Classifier-master>python extract_features.py
2021-11-28 16:18:15.009589: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-11-28 16:18:15.009975: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

(base) C:\Users\Admin\Desktop\COVID-Classifier-master>



it is ok ? I've got result? pneumonia.mat is ok ?

thanks
