### ISSUE TITLE
evaluate_features.py

### ISSUE THREAD

**Issue by kirillportfolio** [abzargar/COVID-Classifier#5]
How to solve this error ?

(base) C:\Users\Admin\Desktop\COVID-Classifier-master>python evaluate_features.py
Traceback (most recent call last):
  File "evaluate_features.py", line 28, in <module>
    scores=np.concatenate((covid_features[:,:-1],normal_features[:,:-1],pneumonia_features[:,:-1]), axis=0)
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 252 and the array at index 2 has size 0

(base) C:\Users\Admin\Desktop\COVID-Classifier-master>

**Comment by kirillportfolio** [comment]
hello... anybody is here?
